import * as fs from "fs";
import * as path from "path";
import { task } from "hardhat/config";

/**
 * Exports ABIs and deployment addresses into `@sable/config`.
 *
 * The web app and the indexer never read Hardhat artifacts directly and never hold their
 * own copy of an address. Both import from `@sable/config`, and this task is the only
 * thing that writes it — so "which address is the frontend using?" always has exactly one
 * answer.
 */

const CONTRACTS = [
  { name: "Sable", source: "Sable.sol", exportName: "sableAbi" },
  { name: "SableConfidentialUSD", source: "token/SableConfidentialUSD.sol", exportName: "confidentialAssetAbi" },
  { name: "SableTestnetYieldAdapter", source: "adapters/SableTestnetYieldAdapter.sol", exportName: "yieldAdapterAbi" },
  { name: "SableReserveYieldAdapter", source: "adapters/SableReserveYieldAdapter.sol", exportName: "reserveAdapterAbi" },
] as const;

const HEADER = `// AUTO-GENERATED by \`pnpm sync:abis\`. Do not edit by hand.
// Regenerate after any change to the contracts or a redeployment.
`;

task("sync:abis", "Exports ABIs and deployment addresses into @sable/config").setAction(
  async (_args, hre) => {
    const root = path.resolve(hre.config.paths.root, "../..");
    const outDir = path.resolve(root, "packages/config/src/generated");
    fs.mkdirSync(outDir, { recursive: true });

    // 1. ABIs -------------------------------------------------------------------
    const exports: string[] = [];

    for (const contract of CONTRACTS) {
      const artifactPath = path.resolve(
        hre.config.paths.artifacts,
        "contracts",
        contract.source,
        `${contract.name}.json`,
      );

      if (!fs.existsSync(artifactPath)) {
        throw new Error(`Artifact missing for ${contract.name}. Run \`pnpm contracts:compile\` first.`);
      }

      const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8")) as { abi: unknown[] };
      const file = path.join(outDir, `${contract.exportName}.ts`);

      fs.writeFileSync(
        file,
        `${HEADER}\nexport const ${contract.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
      );

      exports.push(`export { ${contract.exportName} } from "./${contract.exportName}";`);
      console.log(`  abi   ${contract.name} (${artifact.abi.length} entries)`);
    }

    // 2. Deployments ------------------------------------------------------------
    const deploymentsDir = path.resolve(root, "deployments");
    const deployments: Record<string, unknown> = {};

    if (fs.existsSync(deploymentsDir)) {
      for (const entry of fs.readdirSync(deploymentsDir)) {
        if (!entry.endsWith(".json")) continue;
        const name = entry.replace(/\.json$/, "");
        deployments[name] = JSON.parse(fs.readFileSync(path.join(deploymentsDir, entry), "utf8"));
        console.log(`  addr  ${name}`);
      }
    }

    fs.writeFileSync(
      path.join(outDir, "deployments.ts"),
      `${HEADER}
import type { SableDeployment } from "../types";

/**
 * Deployment records, keyed by Hardhat network name. Empty until \`deploy:sable\` has run.
 */
export const deployments: Record<string, SableDeployment> = ${JSON.stringify(deployments, null, 2)};
`,
    );
    exports.push(`export { deployments } from "./deployments";`);

    fs.writeFileSync(path.join(outDir, "index.ts"), `${HEADER}\n${exports.join("\n")}\n`);

    console.log(`\nWrote ${path.relative(process.cwd(), outDir)}`);
    if (Object.keys(deployments).length === 0) {
      console.log("No deployments yet — run `pnpm deploy:sepolia` to populate addresses.");
    }
  },
);
